### ISSUE TITLE
copy HTML does not put page title in HTML

### ISSUE THREAD

**Issue by jeske** [kiichi/QuickCopyTitleAndURL#1]
for example, on this page..

"Copy [title] URL" produces this output...

`[New Issue · kiichi/QuickCopyTitleAndURL] https://github.com/kiichi/QuickCopyTitleAndURL/issues/new
`

"Copy HTML" produces this output, where the URL is used instead of the page title...

`<a href="https://github.com/kiichi/QuickCopyTitleAndURL/issues/new">https://github.com/kiichi/QuickCopyTitleAndURL/issues/new</a>
`

But I expect it to produce this output, where the URL is the ref and the page title is the link content

`<a href="https://github.com/kiichi/QuickCopyTitleAndURL/issues/new">New Issue · kiichi/QuickCopyTitleAndURL</a>
`

**Comment by kiichi** [comment]
Thank you for reporting this!

Fixed and published a new version 1.1.0.  #2
Please update your extension.

![Mar-16-2019 11-34-54](https://user-images.githubusercontent.com/396816/54477767-3130b480-47e1-11e9-912d-6d413409fa61.gif)

**Comment by jeske** [comment]
Awesome!

It would be really great if the extension had an additional "Copy Link"
option, which would create a rich text clipboard with a live html link,
rather than the current situation which creates a clipboard with the HTML
code of a link. This would paste as an active link into rich-text capable
fields (both content-editable regions in web pages, and rich text desktop
apps), instead of the current "copy html" which pastes as the HTML code.
For example, this would paste into gmail, google docs, or MSWord as an
actual link. This is the primary style I'd like to use all the time.

This is done by injecting the HTML into a DOM document so that it's parsed
into a dom element (or by manually creating the A-href element), selecting
the DOM element content, and then copying that to the clipboard.

Chrome changes the extension security model periodically, so I'm not sure
what is required to do this today... if I get some time I'll try to make a
patch that adds this.

**Comment by kiichi** [comment]
Ah it make sense. could you check if this is ok?

https://github.com/kiichi/QuickCopyTitleAndURL/pull/3#issue-262695313

**Comment by kiichi** [comment]
@jeske I just deployed it on store. It should be available in an hour. The latest version is 1.2.0, and look for a new menu "Copy Rich Text Link". 

Using Chrome...

- Office 365 - OK
- Hotmail - OK
- TextEdit (Mac Rich Text Editor) - OK
- Confluence - OK
- Google Doc - OK
- Gmail - OK

I tested a few times, it looks ok (initially my test failed for google docs because they only accept https://... or http://...  links)

**Comment by jeske** [comment]
I got the new version, and the new "Copy Rich Text Link" is perfect.. it
works for me everywhere, including gmail and google docs..

That's exactly what I've wanted for many many years. Thanks, now I can
paste this pre-made page-title links without so much annoying work!

Thanks!

Do you have a donation page? Or an email address I can paypal a donation to?

**Comment by kiichi** [comment]
Thank you for generous offer, but don't worry. I would use the new feature too. I appreciate your feedback! @jeske
