### ISSUE TITLE
idea: Integrate with right-click menu

### ISSUE THREAD

**Issue by alejandro5042** [kiichi/QuickCopyTitleAndURL#12]
Self-explanatory :)

If you right click on a non-link, it'd be for the page (as if you pressed the extension button).

**Comment by kiichi** [comment]
I'll definitely look for this feature along with keyboard shortcut. It's better to have more way to access.

**Comment by kiichi** [comment]
Note for my self: [chrome.contextMenus - Google Chrome](https://developer.chrome.com/extensions/contextMenus)

**Comment by kiichi** [comment]
#15
