### ISSUE TITLE
Font Size is too big in Version 1.5.0

### ISSUE THREAD

**Issue by smaragdus** [kiichi/QuickCopyTitleAndURL#16]
@kiichi 

For me [Copy Cat](https://github.com/kiichi/QuickCopyTitleAndURL) is an indispensable extension- since I discovered it I have been using it daily, I have clicked the nice cat toolbar button innumerable times. For me it was close to perfect. Until version [1.5.0](https://github.com/kiichi/QuickCopyTitleAndURL/releases/tag/v1.5.0). I liked the old pop-up window:

**Copy Cat** _version_ **1.4.3**

![Copy Cat 1 4 3 - 2020-05-18 - 002](https://user-images.githubusercontent.com/9025757/82225121-6e388f80-992d-11ea-8ffd-3fb08c91e28f.png)

which was very compact. While I find the new pop-up window:

**Copy Cat** _version_ **1.5.0**

![Copy Cat 1 5 0 - 2020-05-18 - 002](https://user-images.githubusercontent.com/9025757/82225327-bbb4fc80-992d-11ea-908c-9ed1385fd260.png)

too large.

I found old **CRX** files at [Crx4Chrome](https://www.crx4chrome.com/extensions/andlmjmbnlaamloflnelcafcnkiplhkc/), uninstalled version  **1.5.0** and installed version **1.4.3**. In attempt to disable automatic update I went to **andlmjmbnlaamloflnelcafcnkiplhkc** sub-folder, opened **manifest.json** and edited this line:

`"update_url": "https://clients2.google.com/service/update2/crx",`

changing it to:

`"update_url": "https://localhost",`

For the time being the extension has not been updated but I have no idea whether this workaround will work in the long run.

I am aware that someone requested bigger font (#13) so I suppose that the best solution would be if [Copy Cat](https://github.com/kiichi/QuickCopyTitleAndURL) has options where the users would be able to specify which pop-up interface they would like to use:

- the old one- smaller font, All Tabs on the right;

or:

- the new one- bigger font, All Tabs on the left;

I definitely prefer the old interface with smaller font and All Tabs on the right. I also do not need the last used command to be remembered as I use almost all copy commands alternately. If options are implemented there might be a check box:

- Remember last used command

If execution of copy commands via context menu (#12) is implemented there might be anotheer check box in Options:

- Context menu integration

Regards

**Comment by kiichi** [comment]
Hi @smaragdus , thank you for using Copy Cat. I'll make settings screen this week, and how about I'll make this configurable in this way:

- Font Size or choose different layout to render menu
- All Tabs left or right

Another person mention the usage like you said here, 

>  I use almost all copy commands alternately

I'll also make copy command configurable.

> Context menu integration

Is this mean, turn on / off context menu from the settings? That's possible too.

I also see the glitch on your screenshot, little space under all tabs.

**Comment by smaragdus** [comment]
@kiichi 

Thank you for your quick response and for considering my suggestion about extension options!

> I'll make settings screen this week, and how about I'll make this configurable in this way:
> 
> - Font Size or choose different layout to render menu
> - All Tabs left or right

This will be excellent!

> I'll also make copy command configurable.

Nice!

> Is this mean, turn on / off context menu from the settings? That's possible too.

Yes, this is exactly what I mean. I would like to be able to access copy commands via context menu but I suppose that some users would prefer just to execute the copy commands via the toolbar button, this would be the case when users have too many extensions and the context menu becomes cluttered. Below I will show examples of 2 other extensions which have option to enable/disable context menu integration:

- [EditThisCookie](https://github.com/ETCExtensions/Edit-This-Cookie):

![EditThisCookie 1 5 0 - 2020-05-19 - 003](https://user-images.githubusercontent.com/9025757/82358657-7d900980-9a0f-11ea-81ce-10ff460c719b.png)

- [Reading List](https://github.com/alexpdraper/reading-list)

![Reading List 2 4 4 - 2020-05-19 - 003](https://user-images.githubusercontent.com/9025757/82358700-8e407f80-9a0f-11ea-87f2-85aec492ceeb.png)

I suppose that:

- Show in context menu

check box would be fine.

I suppose that context menu will be implemented with sub-menus for copy commands. I will show you how a similar extension- [Copycat](https://github.com/BlackGlory/copycat), handles context menu integration:

![Copycat 2 4 2 - 2020-05-19 - 004](https://user-images.githubusercontent.com/9025757/82360070-808bf980-9a11-11ea-9153-7428fa65fb82.png)

I was about to suggest implementation of context menu myself but I didn't because I was afraid that I would overburden you with too much work.

I am glad that you still have time and motivation to maintain and improve your excellent extension!

Best regards

**Comment by smaragdus** [comment]
I saw that context menu integration was implemented in version [1.6.0](https://github.com/kiichi/QuickCopyTitleAndURL/releases/tag/v1.6.0). I tested it and it works fine.

I suppose that you may consider to shorten a bit the context menu entry:

![Copy Cat 1 6 0 - 2020-05-20 - 005](https://user-images.githubusercontent.com/9025757/82450161-0319c500-9ab5-11ea-8b94-3983523e1691.png)

In stead of:

`Copy Cat - Quick Copy Title and URL`

just:

`Copy Cat`

I suppose that those who have installed the extension know what it is doing and the description- `Quick Copy Title and URL` is not that needed.

Thank you for your great work!

Regards

**Comment by alejandro5042** [comment]
Yes thank you for working on this extension! I love the attention to polish and quality.

**Comment by kiichi** [comment]
Thanks for all feedbacks, I start implementing Settings screen. At least, in the next release 1.7.0 (eta Monday), you can put "Small" font size and "All Tabs" on right again @smaragdus 

I'm also looking into where the long text in context menu coming from... it is coming from the manifest of the app, so I shorten it. I'm working on context menu On / Off option now, expecting to release something tomorrow. I'll keep you posted here.

#17 

<img width="582" alt="CopyCat_Settings" src="https://user-images.githubusercontent.com/396816/82740748-b4b93000-9d19-11ea-8383-a58ec6d7c652.png">

P.S. For even larger screen folks, I created "Large" Option. @alejandro5042 

<img width="357" alt="CopyCat_Settings" src="https://user-images.githubusercontent.com/396816/82740844-6f493280-9d1a-11ea-8f3c-08bdaa2dfd7f.png">

**Comment by kiichi** [comment]
Lol how come I didn't realized that exact same name and similar plugin exists out there...? he could be my brother in previous life... 

https://github.com/BlackGlory/copycat

I might change the name of this plugin if that causes some issue

**Comment by kiichi** [comment]
@smaragdus the latest version 1.7.0 is available now. Please go to settings, and set Size to Small and All Tabs on right side. If you need even smaller size, let me know.

**Comment by smaragdus** [comment]
@kiichi 

First, thank you for your excellent work! I saw that version 1.7.0 was released yesterday and I even tested it but did not have time to reply here. Layout tab in Settings is exactly what I needed and now the pop-up window is exactly to my taste, screen:

![Copy Cat 1 7 0 - 2020-05-25 - 002](https://user-images.githubusercontent.com/9025757/82827420-ac96f700-9eb7-11ea-94db-01fb6cc23af3.png)

The context menu is also fine, screen:

![Copy Cat 1 7 0 - 2020-05-25 - 010](https://user-images.githubusercontent.com/9025757/82827744-4eb6df00-9eb8-11ea-95d8-6fb2b67df24c.png)

> Lol how come I didn't realized that exact same name and similar plugin exists out there...? he could be my brother in previous life...

The name is not exactly the same- your extension is **Copy Cat** while the other one is **Copycat**.

> I might change the name of this plugin if that causes some issue

Please don't- the name of your extension and its icon are nice!

I think I found a small issue- the text in Layout tab in Settings does not fit the check-boxes, screen:

![Copy Cat 1 7 0 - 2020-05-25 - 005](https://user-images.githubusercontent.com/9025757/82828105-0815b480-9eb9-11ea-9856-55265bf4a280.png)

The lower part of the text looks truncated. Can you confirm this or this appears on my browser only?

Thank you very much for your great work!

Regards

**Comment by kiichi** [comment]
OK thank you for screenshots @smaragdus  some strange things are happening in Windows. 

I'm using PureCSS framework and it should normalize all, but maybe I forgot meta tag's viewport settings... I have extra Windows laptop here, and I'll double check on that. I'll have design updates one more time.

**Comment by kiichi** [comment]
That little white line below the all tabs was fixed... that was the checkmark , UTF font,  rendered differently in Windows. I just shrink to make sure doesn't push.

![image](https://user-images.githubusercontent.com/396816/82914030-07266680-9f3d-11ea-9f22-cc6d6f12e53e.png)

Font size in the settings page... I blame PureCSS framework, somehow it works correctly when I nested inside the grid. That's odd, form elements are nothing to do with grid though, but I'm just taking their example.

![image](https://user-images.githubusercontent.com/396816/82914673-cc70fe00-9f3d-11ea-94fe-a374160aaacd.png)

https://github.com/kiichi/QuickCopyTitleAndURL/pull/17/commits/5e99825cc3abecac6798c240cf9fa450068e9cf5

Both Screenshots were taken in Windows 10 Pro, and I tested zoom in / zoom out too. I'll give another update today. @smaragdus

**Comment by smaragdus** [comment]
@kiichi 

I am using [Cent Browser](https://www.centbrowser.com/) [version](https://www.centbrowser.com/history.html) **4.2.10.171** (based on **Chromium** version **80.0.3987.163**) on Windows 8 x64. If needed I may check the extension with another Chromium-based browser, I also have [Vivaldi](https://vivaldi.com/).

Regards

**Comment by kiichi** [comment]
Version 1.7.1 is released. Thank you

**Comment by smaragdus** [comment]
@kiichi 

Excellent work, as usual!

Text in text boxes is no longer truncated, screen:

![Copy Cat 1 7 1 - 2020-05-27 - 003](https://user-images.githubusercontent.com/9025757/83033412-bcd9de00-a03f-11ea-8ade-fe8ba00a9e72.png)

Many thanks!

Best regards
