### ISSUE TITLE
Not appearing in toolbar

### ISSUE THREAD

**Issue by danvk** [kiichi/QuickCopyTitleAndURL#20]
I see CopyCat in the context menu just fine:

![image](https://user-images.githubusercontent.com/98301/87947261-132c3180-ca71-11ea-8d0a-87e8db025afd.png)

But the button isn't appearing in my toolbar:

![image](https://user-images.githubusercontent.com/98301/87947336-2d660f80-ca71-11ea-95cc-39bfe2155666.png)

which is a bummer because I think the "all tabs" feature is in there, and that's why I want this extension! Any ideas? Thanks!

**Comment by danvk** [comment]
Nevermind, I needed to "pin" the extension:

![image](https://user-images.githubusercontent.com/98301/87947488-669e7f80-ca71-11ea-96ef-156e8b6143b4.png)

**Comment by kiichi** [comment]
@danvk thank you for using the extension and feedback, sorry I missed your message. Yes I also noticed that Chrome put some extension back and forth when it gets updated new version / re-login after while.
