### ISSUE TITLE
New Copy Format

### ISSUE THREAD

**Issue by smaragdus** [kiichi/QuickCopyTitleAndURL#4]
Hello,

I like your extension very much, excellent job, thank you.

I would like to suggest a new format for copying Title and URL:

besides the current formats (single line formats - Title and URL in the same line):

- `Title - URL`
- `[Title] URL`

there is new format (two lines format - Title and URL in separate lines):

- `Title`
`URL`

Example:

**Current formats:**

- GitHub - https://github.com/
- [GitHub] https://github.com/

**New format:**

- GitHub
https://github.com/

I would prefer this format for saving link of articles- Title and URL in separate lines. Of course I can edit copied content yet automatic copying in this preferred format would be easier and handier to use.

I suppose that such a new format will not require too much work.

Regards

**Comment by kiichi** [comment]
Thanks for using this app! I added a new items "Copy in Two Lines" please get update from Chrome store - probably takes about an hour to propagate.

Version 1.3.0
https://chrome.google.com/webstore/detail/andlmjmbnlaamloflnelcafcnkiplhkc/

![Jun-12-2019 12-45-37](https://user-images.githubusercontent.com/396816/59370251-20c0a500-8d10-11e9-8825-182a02cf96db.gif)

**Comment by smaragdus** [comment]
@kiichi 

Thank you very much! Version **1.3.0** is a significant improvement over the previous version. I have just tested it and **Copy in Two Lines** is exactly what I needed. **All Tabs** feature is also excellent- I myself thought of suggesting it but I supposed that it would require too much work. Now **Copy Cat** is very flexible and exactly to my taste- with a single click I can copy all links in my preferred format. Excellent work, many thanks!

I may suggest some more tiny enhancements in the future.

Regards

**Comment by kiichi** [comment]
Thanks @smaragdus I appreciate any feedbacks!

**Comment by smaragdus** [comment]
@kiichi 

I opened one more [issue](https://github.com/kiichi/QuickCopyTitleAndURL/issues/6), I hope that I am not asking too much.
