### ISSUE TITLE
Copy BBCode

### ISSUE THREAD

**Issue by smaragdus** [kiichi/QuickCopyTitleAndURL#6]
I quite often post to forums which use **BBCode** so for me it would be convenient if **Copy Cat** could copy links in **BBCode**.

**BBCode** uses this tag for **Link (named)**:

`url={url}]{text}[/url]`

- [BBCode tags reference](https://www.bbcode.org/reference.php/)
- [BBCode guide](https://www.phpbb.com/community/help/bbcode)

A couple of examples of **BBCode**:

- **GitHub** - `[url=https://github.com/]GitHub[/url]`
- **DuckDuckGo** - `[url=https://duckduckgo.com/]DuckDuckGo — Privacy, simplified.[/url]`

I suppose that if you choose to add support for **BBCode** you may put it below **Copy Markdown**, example:

- **...**
- **Copy Markdown**
- **Copy BBCode**
- **Copy Title Only**
- **...**

I suppose that support for **BBCode** would be useful for people who frequently post links to forums.

**Comment by kiichi** [comment]
@smaragdus I just uploaded version 1.4.0, and it should be available in a hour or so. Spec and reference are very clear and precise, thank you!

For test rendering, I used this. 

http://www.amigabounty.net/index.php?function=bbcodetest

Tried a few URLs including above examples, look ok. 

![Jun-14-2019 23-56-19](https://user-images.githubusercontent.com/396816/59546867-d2bfc300-8f02-11e9-9915-4757a224766e.gif)


Please update on your extension page after while.

**Comment by smaragdus** [comment]
@kiichi 

This was very fast! Thank you very much! I got version **1.4.1** and `Copy BBCode` works as expected, excellent work! I appreciate when a developer is so helpful and open to suggestions.

Regards
