### ISSUE TITLE
Copy All Tabs - last tab skipped

### ISSUE THREAD

**Issue by smaragdus** [kiichi/QuickCopyTitleAndURL#8]
Hello,

It seems that there is a bug when executing **All Tabs** commands- the last tab URL is not copied. Example- if I open 5 tabs and I execute any of **Copy All Tabs** commands the last tab, the 5th tab from left to write is not copied. As a workaround I have to open a blank 6th tab to get all 5 tabs copied. This happens with **Copy Cat** version **1.4.1**. Please confirm the problem.

Regards

**Comment by kiichi** [comment]
@smaragdus Thank you for the feedback, I was able to reproduce the issue. I'll work on it this weekend :)

**Comment by kiichi** [comment]
@smaragdus I just uploaded Version 1.4.2. It should be available in hour or so. Have a nice weekend!

<img width="1419" alt="Microsoft_Teams_Notification_and__No_Name____-_VIM2_and__No_Name____-_VIM1" src="https://user-images.githubusercontent.com/396816/60371999-1f0e0700-99c9-11e9-83a2-1ba6e021e697.png">

**Comment by smaragdus** [comment]
@kiichi 

Thank you very much for the fast response and for the quick fix! Version **1.4.2** seems to work as expected. If it happens that I find some problems in the future I will let you know again. Your support is excellent!

Best regards and have a great weekend too!
