### ISSUE TITLE
automatically filter leading "(5)" page title prefixes appearing all over now

### ISSUE THREAD

**Issue by jeske** [kiichi/QuickCopyTitleAndURL#9]
First off, I want to say THANK YOU for CopyCat.. I suggested the "Copy Rich Text Link" feature, and you added it, and I now use this extension literally hundreds of times every day. It's that important to me. FYI, my most common is by far "rich text", but I also frequently use "markdown", mostly for github links.

And now for my suggestion.  (which I'm glad to add myself when I get a little time)

It seems a bunch of websites all over the web are starting to prefix page titles with "(4)", where the number is the number of outstanding notifications you have on that site, or comments on that page, and other random garbage. This doesn't really matter, but when copying urls with CopyCat, it's a constant nuisance, as I have to delete these numbers from the beginning of URLs all the time.

For example, here is a video explaining why these numbers appear on youtube... copied with copycat to markdown:

[(9) What are Numbers Appearing On Browser Tab title of YouTube tabs? (strange index numbers on YT tabs) - YouTube](https://www.youtube.com/watch?v=bV0QNuhN9fU)

I would like copycat to just regex match and remove a leading pattern `(\([0-9]+\) )?`, so the above URL would automatically be copied as:

[What are Numbers Appearing On Browser Tab title of YouTube tabs? (strange index numbers on YT tabs) - YouTube](https://www.youtube.com/watch?v=bV0QNuhN9fU)

**Comment by kiichi** [comment]
Uploading to the web store, the version would be 1.4.3

**Comment by kiichi** [comment]
Version 1.4.3 has been approved, Thank You for your help @jeske !

**Comment by kiichi** [comment]
Another useful example in Atlassian products like Confluence

<img width="145" alt="_2__Volunteer_App_-_Web_App_Development_-_LIU_Docs" src="https://user-images.githubusercontent.com/396816/81718686-0b855680-944a-11ea-8ad4-375c8eaae441.png">
